### ISSUE TITLE
fdkaac and qaac - licence conflicts?

### ISSUE THREAD

**Issue by vonH** [jlw4049/FFMPEG-Audio-Encoder#19]
Hello,

The licences for both fdkaac and qaac are confusing, and generally indicate that neither should be bundled (only when compiled), although there are different opinions. For example, Debian classes fdkaac as "non-free" software due to licence restrictions. Additionally, projects such as Staxrip (and other GUIs for encoding) have already removed both. Is this a non-issue for this project?

Regards,
Piers

**Comment by jlw4049** [comment]
After this weekend I'll further read into the license for both encoders. You are right staxrip has removed these in later versions. 

I'll read up on it. If I have to remove then from the bundle I'll have to reprogram a small chunk of the program that requires the user to add these codecs in order to utilize them. 

If you have more information I'll gladly look into it as well. After this long work weekend I'll take a look at this.

**Comment by jlw4049** [comment]
Upon further reading, a few "non-free" libraries are needed from apple for QAAC to actually run. FDK-AAC also cannot be included either. I will take the time to make the program look for these needed files upon launch or something of that nature. That way the user can still use these codecs if they can provide a way to get the proper DLL.s or exes (in fdk-aac's case)

Luckily staxrip authors has already written a wiki about how to extract it with a nice little script for QAAC 
https://github.com/staxrip/staxrip/wiki/qaac

FDK-AAC has to be compiled by the user in order to utilize it. I will try to work on this in the next little while, I'm feeling a little under the weather atm with some virus's going around. Thanks for pointing this out!

**Comment by vonH** [comment]
Personally, I have qaac and fdkaac in a directory on a separate drive so I can always point applications to them. The licencing model is far too complicated for it to be considered reasonable.

**Comment by jlw4049** [comment]
> Personally, I have qaac and fdkaac in a directory on a separate drive so I can always point applications to them. The licencing model is far too complicated for it to be considered reasonable.

I haven't begun work on this yet, but I do have some plans/fixes/stuff coming to the audio encoder. I'll include all the changes we have discussed.

**Comment by jlw4049** [comment]
Everything we discussed has been changed with these files, see release/notes
https://github.com/jlw4049/FFMPEG-Audio-Encoder/releases/tag/4.0
