### ISSUE TITLE
Drag n' drop folders in the file batch window results in error

### ISSUE THREAD

**Issue by PODxt** [jlw4049/FFMPEG-Audio-Encoder#33]
Running v4.04

File -> File Batch -> Drag n' drop a folder icon containing 5 .wav files (2 channels, 44.1 kHz,16 bits) from Windows into the Batch File Input window

Results in a "Traceback error"
Exception in thread Thread-445:Traceback (most recent call last):File "threading.py", line 932, in _bootstrap_innerFile "threading.py", line 870, in runFile "FFMPEGAudioEncoder.py", line 10960, in process_batch_file_input_informationFile "pymediainfo\__init__.py", line 496, in parseRuntimeError:An error occured while opening F:\Flac\Test with libmediainfo

Files are loading correctly when the folder is opened, all files selected and then drag n' dropped into the Batch File Input window.

On a side note, the batch processor also stops working when there are double spaces or special characters like + in the file name.

**Comment by PODxt** [comment]
Sure: https://www.mediafire.com/file/fsdu4ylqlqy5u6b/New_folder.zip/file

Try to drag n' drop the folder and try also to select all the files within this folder, drag n' drop them and then convert them.

**Comment by jlw4049** [comment]
I am definitely able to replicate the errors. I'll get a fix out for this most likely tomorrow sometime.

**Comment by jlw4049** [comment]
I've fixed half of the issue here. Tomorrow I'll work through the other issue, it's not actually erroring out with files names that have "+" operators in it, it actually has to do with the double space in the file name.

Clap**SPACESPACE**+phat_01.L_ - Copy.wav

Currently the way I'm sending the command to be executed actually strips all double white spaces out of the entire command string. I see now this is problematic and will require a little more work than I thought to adjust how all of the commands are sent. 

I should still have a fix out for this tomorrow.

**Comment by jlw4049** [comment]
This should be solved as of v4.05

https://github.com/jlw4049/FFMPEG-Audio-Encoder/releases/tag/4.05

Please provide feedback, thank you,

**Comment by PODxt** [comment]
I just tested with a folder containing 200 wav files to convert to flac , drag n' dropped it into the batch window, and everything worked as intended. Thank you Jessie!

**Comment by jlw4049** [comment]
No problem! Let me know if you run into anything else!
